### ISSUE TITLE
Command "queue:work" is not defined.   

### ISSUE THREAD

**Issue by sbsbessa** [orobogenius/sansdaemon#10]
On this project we're still at Lavarel 5.2 and needed the exact features your code provides, however it does not seem to work.
As soon as we add `Queueworker\SansDaemon\SansDaemonServiceProvider::class` to our `config/app.php` the `queue:work` command is no longer available.
Adding the `SansDaemonServiceProvider` before the `QueueServiceProvider` the command is available but without the `--sansdaemon` option.

**Comment by orobogenius** [comment]
@sbsbessa Thanks for bringing up the issue with Laravel 5.2 but at this time the package does not currently have support for Laravel 5.2 and so the command won't work.

This is mostly because of structural changes (from 5.2 to newer versions of Laravel) in the way the work command is being registered and also API changes in the work command itself.

The minimum required version is Laravel 5.4.
