### ISSUE TITLE
difference with this command php artisan queue:work --stop-when-empty

### ISSUE THREAD

**Issue by matiazar** [orobogenius/sansdaemon#24]
Hi. great job... 
but i have a question to know what to use in my case

whats the difference with this package and this command
php artisan queue:work --stop-when-empty

thanks in advance!

**Comment by orobogenius** [comment]
@matiazar this package was developed before Laravel 5.7 which is when the `--stop-when-empty` option was introduced. Before then, the queue worker only supported the full daemon mode to run queues and that wasn't great for cases where you have limited time to process queue on the job because of limitation on the server or when not using it in CLI SAPI.

**Comment by matiazar** [comment]
@orobogenius thanks for answering me !
