### ISSUE TITLE
Why do you need this package?

### ISSUE THREAD

**Issue by weblabio** [orobogenius/sansdaemon#32]
I was looking for a solution for an old version 5.5 and found this package. But why is it needed? If since 5.7 this functionality is already in the framework (--stop-when-empty flag)? The package is only useful for the old version. I am wrong?

Since version 1.2.0 the package requires illuminate/support ^6.0

[https://laravel.com/docs/5.7/queues#running-the-queue-worker](https://laravel.com/docs/5.7/queues#running-the-queue-worker)
```
Processing All Queued Jobs & Then Exiting
The --stop-when-empty option may be used to instruct the worker to process all jobs 
and then exit gracefully.
```

**Comment by orobogenius** [comment]
Hi @weblabio, you're right, `--stop-when-empty` has since been added to laravel and does exactly the primary function of this package. If you're using an older version of laravel then this package works well. However, that isn't the only use for the package. The package is still very much useful in shared hosting environments where the process execution time is limited. You can specify the maximum execution time (`--max_exec_time`) based on how long the hosting provider allows you to run processes and the package will process your jobs and gracefully exit before the time is up.
